### ISSUE TITLE
Colab notebook giving error

### ISSUE THREAD

**Issue by madrainbo** [OPHoperHPO/image-background-remove-tool#23]
Hi There
After your recent update, I tried to run the colab notebook to check the improvements over the earlier release. 
However, currently it is giving error: (Note: I was using my own image, instead of the default one already present)
```
Traceback (most recent call last):
  File "main.py", line 152, in <module>
    cli()
  File "main.py", line 148, in cli
    process(input_path, output_path, model_name, preprocessing_method_name, postprocessing_method_name)
  File "main.py", line 102, in process
    preprocessing_method = preprocessing.method_detect(preprocessing_method_name)
  File "/content/image-background-remove-tool/libs/preprocessing.py", line 40, in method_detect
    return BoundingBoxDetectionFastRcnn()
  File "/content/image-background-remove-tool/libs/preprocessing.py", line 57, in __init__
    self.__fast_rcnn__ = FastRcnn()
  File "/content/image-background-remove-tool/libs/preprocessing.py", line 361, in __init__
    from gluoncv import model_zoo, data
ModuleNotFoundError: No module named 'gluoncv'
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-cc04411fc9c1> in <module>()
     16   f = "1.jpg"
     17   get_ipython().system('python main.py -i ./1.jpg -o ./2.png -m $model_name -prep $preprocessing -postp $postprocessing')
---> 18   image = Image.open("./2.png")
     19   new = Image.new("RGB", image.size, (255, 255, 255))
     20   new.paste(image, (0,0), image)

/usr/local/lib/python3.6/dist-packages/PIL/Image.py in open(fp, mode)
   2807 
   2808     if filename:
-> 2809         fp = builtins.open(filename, "rb")
   2810         exclusive_fp = True
   2811 

FileNotFoundError: [Errno 2] No such file or directory: './2.png'
```

**Comment by OPHoperHPO** [comment]
Hello, @madrainbo. Try resetting the colab container and starting the installation again.

**Comment by OPHoperHPO** [comment]
Hello, @madrainbo.
Judging by the log, the program installation process was unsuccessful.
Try resetting the colab container and starting the installation again.
In addition, if you are trying to check out release 3.3, which is in an `untested` branch, then you will need a new notebook from the same branch. Links in readme do not work yet.

**Comment by madrainbo** [comment]
Tried today with the updated file and it worked fine. I also see improvement on the result side.
