### ISSUE TITLE
Getting some error related to setup. 

### ISSUE THREAD

**Issue by PkTheDataScientist** [OPHoperHPO/image-background-remove-tool#32]
Hi, I am new to Python. I am trying to implement your code. There were few dependencies such as VC++ and Torch that I am able to install and move forward but I am not able to move forward after this error. Online forums talk about including some path in environment variables, but it seems like a very common error and in reference to your code which library it is seeking am not sure. I would greatly appreciate it if you could help and advise on this error. Thank you. 

C:\Users\pk_pk\Desktop\Mytr\image-background-remove-tool-master>python main.py -i C:\Users\pk_pk\Desktop\Mytr\Images -o C:\Users\pk_pk\Desktop\Mytr\ImageOutput -m u2net -prep bbd-fastrcnn -postp rtb-bnb
Traceback (most recent call last):
  File "main.py", line 152, in <module>
    cli()
  File "main.py", line 148, in cli
    process(input_path, output_path, model_name, preprocessing_method_name, postprocessing_method_name)
  File "main.py", line 95, in process
    model = model_detect(model_name)  # Load model
  File "C:\Users\pk_pk\Desktop\Mytr\image-background-remove-tool-master\libs\networks.py", line 43, in model_detect
    return U2NET(model_name)
  File "C:\Users\pk_pk\Desktop\Mytr\image-background-remove-tool-master\libs\networks.py", line 56, in __init__
    import torch
  File "C:\Users\pk_pk\anaconda3\lib\site-packages\torch\__init__.py", line 82, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\pk_pk\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by PkTheDataScientist** [comment]
All right. I am able to solve this issue. There was a problem with my Torch Installation. I installed GPU version of Torch using conda, but I was supposed to install CPU version. The following torch version worked with your code. I am successfully able to clean the background of my test image. Thank you so much. 

pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
